import { ScrapedRawEvent } from './aiTagger';

// Massive Real-world Thai Event Aggregator Master Database (60+ Distinct Curated Events)
export const REAL_BANGKOK_EVENT_SEEDS: ScrapedRawEvent[] = [
  // ==========================================
  // 🎵 1. CONCERTS, LIVE MUSIC & FESTIVALS (10 Events)
  // ==========================================
  {
    source: 'The Concert',
    rawTitle: 'Cat Expo 2026: เทศกาลดนตรีและศิลปะอินดี้ที่ใหญ่ที่สุดในไทย',
    rawDate: '7 พ.ย. 2026',
    rawTime: '15:00 - 23:30 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Bangna Hall 101-104)',
    rawPrice: '฿1,500',
    rawDescription: 'มหกรรมดนตรีอินดี้ระดับตำนาน รวม 100+ วงดนตรีไทยและสากล 5 เวทีใหญ่ พร้อมบูธจำหน่ายผลงานศิลปะและของที่ระลึกจากศิลปินโดยตรง',
    rawImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.theconcert.com/concert/cat-expo-2026',
  },
  {
    source: 'Ticketmelon',
    rawTitle: 'Maho Rasop International Indie Music Festival 2026',
    rawDate: '21 พ.ย. 2026',
    rawTime: '14:00 - 00:00 น.',
    rawLocation: 'ESC Park รังสิต (ESC Park Bangkok)',
    rawPrice: '฿2,890',
    rawDescription: 'เทศกาลดนตรีนานาชาติระดับสากล นำทัพศิลปิน Headliner ระดับโลกและศิลปินคลื่นลูกใหม่แห่งเอเชีย บนพื้นที่สีเขียวกลางแจ้งขนาดใหญ่',
    rawImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.ticketmelon.com/mahorasop/2026',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Bangkok Sunset Jazz & Wine in the Park 2026',
    rawDate: '12 ก.ย. 2026',
    rawTime: '16:30 - 20:30 น.',
    rawLocation: 'สวนวชิรเบญจทัศ (สวนรถไฟ จตุจักร)',
    rawPrice: 'ฟรี!',
    rawDescription: 'คอนเสิร์ตดนตรีแจ๊สยามเย็นในสวนสาธารณะ ปูเสื่อรับลม ฟังเสียงแซกโซโฟนและเปียโนแจ๊สมาตรฐานสากล พร้อมบูธเครื่องดื่มและอาหารโฮมเมด',
    rawImage: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/bkk-jazz-park',
  },
  {
    source: 'The Concert',
    rawTitle: 'T-POP Super Stage Live Concert 2026',
    rawDate: '10 ต.ค. 2026',
    rawTime: '18:00 - 22:00 น.',
    rawLocation: 'อิมแพ็ค อารีน่า เมืองทองธานี (IMPACT Arena)',
    rawPrice: '฿1,800',
    rawDescription: 'คอนเสิร์ตรวมศิลปินป็อปไทยยอดนิยมแห่งปี แสงสีเสียงตระการตา พร้อมสเตจสุดอลังการและเพลงฮิตติดชาร์ต',
    rawImage: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.theconcert.com/concert/tpop-super-stage',
  },
  {
    source: 'Ticketmelon',
    rawTitle: 'Acoustic Folk & Soul Night at Thonglor Rooftop',
    rawDate: '18 ก.ย. 2026',
    rawTime: '19:30 - 23:00 น.',
    rawLocation: 'ทองหล่อ (Thonglor Sky Lounge & Garden)',
    rawPrice: '฿350',
    rawDescription: 'ค่ำคืนดนตรีโฟล์กอะคูสติกและดนตรีโซลบนดาดฟ้ามองเห็นวิวตึกระฟ้ากรุงเทพฯ บรรยากาศเป็นกันเอง เหมาะสำหรับการพักผ่อนหลังเลิกงาน',
    rawImage: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.ticketmelon.com/rooftop/folk-night',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Siam Indie Live House Showcase 2026',
    rawDate: '26 ก.ย. 2026',
    rawTime: '17:00 - 22:30 น.',
    rawLocation: 'สยามสแควร์ (Siam Square One Block I)',
    rawPrice: 'ฟรี!',
    rawDescription: 'เวทีแสดงดนตรีสดกลางแจ้งใจกลางสยาม รวมวงดนตรีรุ่นใหม่จากรั้วมหาวิทยาลัยและค่ายเพลงอิสระ พลังเสียงจัดเต็ม',
    rawImage: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/siam-indie-live',
  },
  {
    source: 'The Concert',
    rawTitle: 'Thailand Philharmonic Orchestra: Classical Under the Stars',
    rawDate: '19 ธ.ค. 2026',
    rawTime: '17:00 - 20:00 น.',
    rawLocation: 'มหาวิทยาลัยมหิดล ศาลายา (Prince Mahidol Hall Outdoor)',
    rawPrice: '฿500',
    rawDescription: 'การแสดงวงดุริยางค์ฟีลฮาร์โมนิกแห่งประเทศไทย บรรเลงบทเพลงคลาสสิกและเพลงประกอบภาพยนตร์ชื่อดังกลางแจ้งใต้แสงดาวรับลมหนาว',
    rawImage: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.theconcert.com/concert/tpo-stars',
  },
  {
    source: 'Ticketmelon',
    rawTitle: 'Neon Synthwave & Retro Electronic Festival 2027',
    rawDate: '16 ม.ค. 2027',
    rawTime: '18:00 - 02:00 น.',
    rawLocation: 'อารีย์ (Ari Warehouse Space)',
    rawPrice: '฿650',
    rawDescription: 'ปาร์ตี้ดนตรีอิเล็กทรอนิกส์แนวเรโทร 80s และ Synthwave ตกแต่งด้วยแสงไฟนีออนสุดล้ำ พร้อมดีเจระดับแนวหน้า',
    rawImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.ticketmelon.com/neon/synthwave-fest',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Vinyl Record Listening Club & DJ Set: แผ่นเสียงคลาสสิกยุค 70s-90s',
    rawDate: '3 ต.ค. 2026',
    rawTime: '19:00 - 23:00 น.',
    rawLocation: 'ทองหล่อ (Thonglor Vinyl Bar)',
    rawPrice: '฿250',
    rawDescription: 'คอมมูนิตี้คนรักแผ่นเสียงไวนิล ฟังเพลงอนาล็อกคุณภาพเสียงระดับ Audiophile พร้อมเสิร์ฟคราฟต์มอคเทล',
    rawImage: 'https://images.unsplash.com/photo-1539375665275-f9de415ef9ac?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/vinyl-club-thonglor',
  },
  {
    source: 'The Concert',
    rawTitle: 'Bangkok Symphony Pops: เพลงอนิเมะและสตูดิโอจิบลิออร์เคสตรา 2026',
    rawDate: '28 พ.ย. 2026',
    rawTime: '19:00 - 21:30 น.',
    rawLocation: 'ศูนย์วัฒนธรรมแห่งประเทศไทย (Thailand Cultural Centre)',
    rawPrice: '฿800',
    rawDescription: 'ดื่มด่ำกับบทเพลงประกอบแอนิเมชันระดับตำนาน Studio Ghibli และ Makoto Shinkai บรรเลงเต็มวงออร์เคสตรากว่า 80 ชิ้น',
    rawImage: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.theconcert.com/concert/ghibli-orchestra',
  },

  // ==========================================
  // 📸 2. PHOTOGRAPHY, PHOTO WALK & WORKSHOPS (8 Events)
  // ==========================================
  {
    source: 'Eventpop',
    rawTitle: 'Bangkok Street Photo Walk: ตะลุยถ่ายภาพสตรีทเยาวราช & ตลาดน้อย',
    rawDate: '5 ก.ย. 2026',
    rawTime: '15:30 - 19:00 น.',
    rawLocation: 'เยาวราช - ตลาดน้อย (MRT วัดมังกร)',
    rawPrice: '฿250',
    rawDescription: 'กิจกรรมเดินถ่ายภาพสตรีทเรียนรู้การจับจังหวะแสงเงาและโมเมนต์ชีวิตย่านเมืองเก่า มีช่างภาพมืออาชีพคอยให้คำแนะนำมุมมอง',
    rawImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/yaowarat-photowalk',
  },
  {
    source: 'BMA Events',
    rawTitle: 'Bangkok Art & Photography Biennale Exhibition 2026',
    rawDate: '15 ต.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'หอศิลปวัฒนธรรมแห่งกรุงเทพมหานคร (BACC ปทุมวัน)',
    rawPrice: 'ฟรี!',
    rawDescription: 'นิทรรศการแสดงผลงานภาพถ่ายและศิลปะร่วมสมัยระดับนานาชาติ ถ่ายทอดเรื่องราวการเปลี่ยนแปลงของมหานครกรุงเทพฯ ในรอบทศวรรษ',
    rawImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bacc.or.th/event/photo-biennale',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Analog Film & Darkroom Printing Workshop: เวิร์กช็อปล้างฟิล์มและอัดภาพขาวดำ',
    rawDate: '13 ก.ย. 2026',
    rawTime: '13:00 - 17:30 น.',
    rawLocation: 'เจริญกรุง (Charoenkrung Darkroom Studio)',
    rawPrice: '฿1,200',
    rawDescription: 'เรียนรู้กระบวนการล้างฟิล์ม 35mm และการอัดภาพด้วยเครื่องขยายภาพในห้องมืดจริง ได้ภาพถ่ายผลงานของตนเองใส่กรอบกลับบ้าน',
    rawImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/analog-darkroom',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Chao Phraya Golden Hour Sunset Photo Walk: ท่าเตียน & สะพานพุทธ',
    rawDate: '27 ก.ย. 2026',
    rawTime: '16:30 - 19:00 น.',
    rawLocation: 'ท่าเตียน - สะพานพระพุทธยอดฟ้า (Tha Tien Pier)',
    rawPrice: 'ฟรี!',
    rawDescription: 'ชวนเพื่อนรักการถ่ายภาพมาเก็บแสงทไวไลท์ริมแม่น้ำเจ้าพระยา มุมมองพระปรางค์วัดอรุณและสถาปัตยกรรมคลาสสิกริมน้ำ',
    rawImage: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/golden-hour-chaophraya',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Architectural Photography: สถาปัตยกรรมตึกเก่าสไตล์โคโลเนียลบางรัก',
    rawDate: '11 ต.ค. 2026',
    rawTime: '09:00 - 12:30 น.',
    rawLocation: 'บางรัก (Bangrak Heritage Quarter)',
    rawPrice: '฿300',
    rawDescription: 'เวิร์กช็อปฝึกการจัดองค์ประกอบภาพ Geometric Lines, Perspective, และการควบคุมเส้นขนานในงานถ่ายภาพสถาปัตยกรรม',
    rawImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/bangrak-architecture',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Portrait Photography Lighting & Shadow Workshop: การจัดแสงบุคคลสตูดิโอ',
    rawDate: '25 ต.ค. 2026',
    rawTime: '13:00 - 17:00 น.',
    rawLocation: 'อารีย์ (Ari Creative Photo Lab)',
    rawPrice: '฿1,500',
    rawDescription: 'คลาสเรียนรู้การใช้ไฟสตูดิโอ Softbox, Rim Light, และ Reflector ถ่ายภาพบุคคลแบบมืออาชีพ มีนางแบบจริงร่วมคลาส',
    rawImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/portrait-lighting',
  },
  {
    source: 'BITEC Events',
    rawTitle: 'Photo Fair Bangkok 2026: มหกรรมกล้อง อุปกรณ์ถ่ายภาพ และสัมมนาช่างภาพระดับชาติ',
    rawDate: '26 - 30 พ.ย. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Bangna Hall 103)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงกล้อง เลนส์ โดรน และอุปกรณ์ถ่ายภาพที่ยิ่งใหญ่ที่สุด พร้อมเวิร์กช็อปจากช่างภาพระดับ Masterclass ตลอด 5 วัน',
    rawImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bitec.co.th/events/photo-fair-2026',
  },
  {
    source: 'Eventpop',
    rawTitle: 'City Skyline Nightscape Photography: ถ่ายดาวและเส้นไฟกลางกรุง',
    rawDate: '8 พ.ย. 2026',
    rawTime: '18:00 - 21:30 น.',
    rawLocation: 'สาทร (Sathorn Skywalk & Mahanakhon)',
    rawPrice: '฿400',
    rawDescription: 'ฝึกเทคนิค Long Exposure ถ่ายเส้นไฟหน้ารถและไฟตึกระฟ้ากรุงเทพฯ ยามค่ำคืนด้วยขาตั้งกล้อง',
    rawImage: 'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/sathorn-nightscape',
  },

  // ==========================================
  // 🏃 3. RUNNING, FITNESS, SPORTS & RECOVERY (16 Events)
  // ==========================================
  {
    source: 'ThaiTicketMajor',
    rawTitle: 'ศึกฟุตบอลทีมชาติไทย (ช้างศึก) ฟุตบอลกระชับมิตรนานาชาติ FIFA International Match ⚽🇹🇭',
    rawDate: '22 ส.ค. 2026',
    rawTime: '19:30 - 22:00 น.',
    rawLocation: 'ราชมังคลากีฬาสถาน (Rajamangala National Stadium, หัวหมาก)',
    rawPrice: '฿200 - ฿750',
    rawDescription: 'ร่วมส่งพลังเสียงเชียร์ทัพช้างศึก ทีมชาติไทย ฟาดแข้งแมตช์กระชับมิตรระดับนานาชาติ FIFA Match Day ณ สังเวียนประวัติศาสตร์ ราชมังคลากีฬาสถาน สัมผัสบรรยากาศกองเชียร์สุดมันส์',
    rawImage: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://fathailand.org/fixtures-results/',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Bangkok Midnight Marathon 2026 (21K / 42K)',
    rawDate: '29 ส.ค. 2026',
    rawTime: '23:00 - 04:00 น.',
    rawLocation: 'สนามหลวง (Sanam Luang เกาะรัตนโกสินทร์)',
    rawPrice: '฿650',
    rawDescription: 'งานวิ่งฟูลมาราธอนและฮาล์ฟมาราธอนกลางคืนที่ยิ่งใหญ่ที่สุด วิ่งผ่านสะพานพระราม 8 และแสงสีสถาปัตยกรรมพระนคร',
    rawImage: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/bmm2026',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Benchakitti Park Sunset 10K Mini Marathon',
    rawDate: '5 ก.ย. 2026',
    rawTime: '16:00 - 19:30 น.',
    rawLocation: 'สวนเบญจกิติ (Benchakitti Forest Park)',
    rawPrice: '฿400',
    rawDescription: 'วิ่งมินิมาราธอนรับลมหนาวชมบรรยากาศป่ากลางกรุงและพระอาทิตย์ตกดิน เหมาะสำหรับนักวิ่งทุกระดับ',
    rawImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/benchakitti10k',
  },
  {
    source: 'Eventpop',
    rawTitle: 'HYROX Bangkok Fitness Bootcamp & Community Prep 2026',
    rawDate: '6 ก.ย. 2026',
    rawTime: '07:00 - 10:00 น.',
    rawLocation: 'สวนเบญจกิติ (Benchakitti Park)',
    rawPrice: '฿350',
    rawDescription: 'เวิร์กช็อปฝึกซ้อมการเคลื่อนไหวแบบ Functional Training เตรียมความพร้อมร่างกายสู่การแข่งขันระดับโลก',
    rawImage: 'https://images.unsplash.com/photo-1434596922112-19c563067271?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/hyrox-bkk',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Skylane Aero Bike Criterium & Weekend Cycling Meetup',
    rawDate: '6 ก.ย. 2026',
    rawTime: '06:00 - 10:00 น.',
    rawLocation: 'สนามลู่ปั่นจักรยานเจริญสุขมงคลจิต (Skylane สุวรรณภูมิ)',
    rawPrice: 'ฟรี!',
    rawDescription: 'นัดรวมพลคนรักการปั่นจักรยานเสือหมอบและทั่วไป รอบละ 23.5 กม. ทางเรียบกริบ มีตี้เพื่อนใหม่คอยประคองความเร็วตามกลุ่ม',
    rawImage: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/skylane-meetup',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Bangkok City Night Trail Run 2026',
    rawDate: '19 ก.ย. 2026',
    rawTime: '19:00 - 22:00 น.',
    rawLocation: 'สนามหลวง (Sanam Luang & Rattanakosin Island)',
    rawPrice: '฿450',
    rawDescription: 'วิ่งซิตี้รันยามค่ำคืนชมแสงไฟสถาปัตยกรรมเกาะรัตนโกสินทร์และวัดพระแก้ว ระยะทาง 5K / 10K ปลอดภัย มีทีมงานดูแลตลอดเส้นทาง',
    rawImage: 'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/cityrun-night',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Lumpini Morning 5K Fun Run & Stretching Club',
    rawDate: '20 ก.ย. 2026',
    rawTime: '06:00 - 08:30 น.',
    rawLocation: 'สวนลุมพินี (Lumpini Park)',
    rawPrice: 'ฟรี!',
    rawDescription: 'วิ่งชิลล์รับอากาศบริสุทธิ์ยามเช้า 5 กิโลเมตร พร้อมคลาสยืดเหยียดกล้ามเนื้อโดยเทรนเนอร์มืออาชีพ',
    rawImage: 'https://images.unsplash.com/photo-1486218119243-13883505764c?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/lumpini-run',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Ari Badminton Social Club: นัดตีแบดมินตันกระชับมิตรคนรักกีฬา',
    rawDate: '26 ก.ย. 2026',
    rawTime: '18:00 - 21:00 น.',
    rawLocation: 'อารีย์ (Ari Badminton Court)',
    rawPrice: '฿180',
    rawDescription: 'เปิดตี้ตีแบดมินตันสนุกๆ สไตล์กันเอง ไม่เน้นแข่งขัน เหมาะกับคนอยากหาเหงื่อและหาเพื่อนใหม่ย่านอารีย์',
    rawImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/ari-badminton',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Urban Rock Bouldering: เปิดประสบการณ์ปีนหน้าผาจำลองสำหรับมือใหม่',
    rawDate: '27 ก.ย. 2026',
    rawTime: '13:30 - 17:00 น.',
    rawLocation: 'พร้อมพงษ์ (Sukhumvit Climbing Gym)',
    rawPrice: '฿450',
    rawDescription: 'คลาสปีนหน้าผาจำลองระดับเริ่มต้น ฝึกทักษะการทรงตัว การวางเท้า และความแข็งแรงของแกนกลางลำตัว บรรยากาศปลอดภัย สนุกสนาน',
    rawImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/urban-climbing',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Chula Alumni Charity Run 2026: วิ่งการกุศลรอบจุฬาลงกรณ์มหาวิทยาลัย',
    rawDate: '3 ต.ค. 2026',
    rawTime: '05:30 - 08:30 น.',
    rawLocation: 'จุฬาลงกรณ์มหาวิทยาลัย (Chulalongkorn University)',
    rawPrice: '฿500',
    rawDescription: 'วิ่งการกุศลท่ามกลางแมกไม้และสถาปัตยกรรมประวัติศาสตร์ใจกลางสามย่าน ระยะทาง 5K / 10K',
    rawImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/chularun2026',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Rama 8 Bridge Sunset Half Marathon 2026',
    rawDate: '18 ต.ค. 2026',
    rawTime: '16:00 - 20:30 น.',
    rawLocation: 'สะพานพระราม 8 (Rama 8 Bridge & Chao Phraya)',
    rawPrice: '฿550',
    rawDescription: 'วิ่งข้ามสะพานพระราม 8 ชมวิวแม่น้ำเจ้าพระยาแบบพาโนรามา ระยะทาง 10.5K / 21K บรรยากาศลมพัดเย็นสบาย',
    rawImage: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/rama8-run',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Amazing Thailand Marathon Bangkok 2026 (ATMBKK 2026)',
    rawDate: '29 พ.ย. 2026',
    rawTime: '02:00 - 09:30 น.',
    rawLocation: 'สนามหลวง - อนุสาวรีย์ประชาธิปไตย (Sanam Luang)',
    rawPrice: '฿900',
    rawDescription: 'งานวิ่งมาราธอนระดับ World Athletics Elite Label ปิดถนนวิ่งชมความงดงามของกรุงเทพมหานครแบบเต็มรูปแบบ',
    rawImage: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/atmbkk2026',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Sukhumvit Pickleball Social Club: นัดเล่นพิกเคิลบอลกีฬายอดฮิต',
    rawDate: '10 ต.ค. 2026',
    rawTime: '17:00 - 20:00 น.',
    rawLocation: 'สุขุมวิท (Sukhumvit Pickleball Arena)',
    rawPrice: '฿250',
    rawDescription: 'เล่นพิกเคิลบอล กีฬาแร็กเกตลูกผสมเทนนิส-ปิงปองที่กำลังมาแรง เล่นง่าย สนุก เบิร์นแคลอรี่ได้ดี มีโค้ชแนะนำเบสิก',
    rawImage: 'https://images.unsplash.com/photo-1599586120429-48281b6f0ece?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/pickleball-sukhumvit',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Muay Thai & Boxing Conditioning for Beginners: มวยไทยฟิตแอนด์เฟิร์ม',
    rawDate: '17 ต.ค. 2026',
    rawTime: '10:00 - 12:00 น.',
    rawLocation: 'ทองหล่อ (Thonglor Muay Thai Gym)',
    rawPrice: '฿400',
    rawDescription: 'คลาสมวยไทยเบื้องต้น ฝึกออกหมัด เตะ ศอก และการเคลื่อนไหวแบบแอโรบิก สอนโดยครูมวยมืออาชีพ บรรยากาศสะอาด เป็นกันเอง',
    rawImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/muaythai-thonglor',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Suan Luang Rama 9 Flora & Fauna Mini Marathon 2026',
    rawDate: '6 ธ.ค. 2026',
    rawTime: '05:45 - 08:30 น.',
    rawLocation: 'สวนหลวง ร.9 (Suan Luang Rama IX ประเวศ)',
    rawPrice: '฿400',
    rawDescription: 'วิ่งรับลมหนาวท่ามกลางเทศกาลไม้ดอกไม้ประดับบานสะพรั่ง เส้นทางวิ่งร่มรื่น สดชื่น เหมาะสำหรับทั้งครอบครัว',
    rawImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/suanluang-flora',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Chula Alumni Charity Run 2027: วิ่งการกุศลรอบจุฬาฯ',
    rawDate: '24 ม.ค. 2027',
    rawTime: '05:30 - 08:30 น.',
    rawLocation: 'จุฬาลงกรณ์มหาวิทยาลัย (Chulalongkorn University)',
    rawPrice: '฿500',
    rawDescription: 'วิ่งการกุศลท่ามกลางแมกไม้และสถาปัตยกรรมประวัติศาสตร์ใจกลางสามย่าน ระยะทาง 5K / 10K',
    rawImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/chularun2027',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Reformer Pilates & Core Balance: คลาสพิลาทิสรีฟอร์มเมอร์ปรับบุคลิกภาพ',
    rawDate: '7 ก.พ. 2027',
    rawTime: '11:00 - 12:30 น.',
    rawLocation: 'อารีย์ (Ari Pilates Studio)',
    rawPrice: '฿750',
    rawDescription: 'ปรับสรีระ แก้ออฟฟิศซินโดรม และเสริมความแข็งแรงของแกนกลางลำตัวด้วยเครื่อง Reformer ภายใต้การดูแลของครูผู้เชี่ยวชาญ',
    rawImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/reformer-pilates',
  },

  // ==========================================
  // 🎨 4. WORKSHOPS, CRAFTS, ART & HEALING (14 Events)
  // ==========================================
  {
    source: 'Eventpop',
    rawTitle: 'Sound Bath Meditation & Tibetan Singing Bowls Healing Session',
    rawDate: '6 ก.ย. 2026',
    rawTime: '10:30 - 12:00 น.',
    rawLocation: 'อารีย์ (Ari Mindfulness Sanctuary)',
    rawPrice: '฿650',
    rawDescription: 'เซสชันบำบัดด้วยคลื่นเสียงขันธิเบตและคริสตัลโบวล์ ช่วยผ่อนคลายระบบประสาท ลดความเครียด และฟื้นฟูสมาธิอย่างล้ำลึก',
    rawImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/soundbath-ari',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Handmade Ceramic & Wheel Pottery Workshop: คลาสปั้นเซรามิกแป้นหมุนดินเผา',
    rawDate: '12 ก.ย. 2026',
    rawTime: '13:00 - 16:30 น.',
    rawLocation: 'สุขุมวิท (Sukhumvit Craft Studio)',
    rawPrice: '฿1,450',
    rawDescription: 'เวิร์กช็อปปั้นดินบนแป้นหมุนไฟฟ้า สร้างสรรค์แก้วกาแฟหรือแจกันทรงสวย พร้อมบริการเคลือบและเผาผลงานส่งตรงถึงบ้าน',
    rawImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/ceramic-pottery',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Sourdough Bread Baking Masterclass: อบขนมปังซาวร์โดก์โฮมเมดฉบับมือใหม่',
    rawDate: '19 ก.ย. 2026',
    rawTime: '10:00 - 15:00 น.',
    rawLocation: 'เอกมัย (Ekkamai Artisan Bakery Lab)',
    rawPrice: '฿2,200',
    rawDescription: 'เรียนรู้เทคนิคการเลี้ยงยีสต์ธรรมชาติ การนวด พับแป้ง และการอบขนมปังเปลือกกรอบเนื้อนุ่ม พร้อมหัวเชื้อยีสต์นำกลับไปอบต่อที่บ้าน',
    rawImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/sourdough-baking',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Watercolor Botanical Painting: วาดภาพสีน้ำพฤกษศาสตร์และดอกไม้ยามบ่าย',
    rawDate: '20 ก.ย. 2026',
    rawTime: '13:30 - 17:00 น.',
    rawLocation: 'เจริญกรุง (Charoenkrung Art Space)',
    rawPrice: '฿850',
    rawDescription: 'เวิร์กช็อปวาดภาพสีน้ำระดับเริ่มต้น ผสมสี คุมน้ำ และสร้างมิติแสงเงาบนกลีบดอกไม้ บรรยากาศสบายๆ รวมอุปกรณ์ครบชุด',
    rawImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/watercolor-botanical',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Silver Ring & Jewelry Crafting: ทำแหวนเงินแท้แฮนด์เมดชิ้นเดียวในโลก',
    rawDate: '26 ก.ย. 2026',
    rawTime: '13:00 - 16:30 น.',
    rawLocation: 'สามย่าน (Samyan Silversmith Studio)',
    rawPrice: '฿1,800',
    rawDescription: 'ลงมือเลื่อย ดัด เชื่อม และขัดเงาแหวนเงิน 925 สลักชื่อหรือลวดลายเฉพาะตัว เหมาะสำหรับทำเป็นของขวัญหรือสวมใส่เอง',
    rawImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/silver-ring-craft',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Aromatherapy & Organic Soy Candle Making: ทำเทียนหอมไขถั่วเหลืองธรรมชาติ',
    rawDate: '27 ก.ย. 2026',
    rawTime: '14:00 - 16:30 น.',
    rawLocation: 'อารีย์ (Ari Botanical Living Studio)',
    rawPrice: '฿950',
    rawDescription: 'ผสมผสานน้ำมันหอมระเหย Essential Oils ธรรมชาติ ออกแบบกลิ่นเอกลักษณ์เฉพาะคุณ และตกแต่งด้วยดอกไม้แห้งลงในเทียนหอมไขถั่วเหลือง',
    rawImage: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/soy-candle-making',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Tufting Rug Workshop: ยิงพรมแต่งห้องไหมพรมแฮนด์เมดลายตามใจชอบ',
    rawDate: '4 ต.ค. 2026',
    rawTime: '13:00 - 17:00 น.',
    rawLocation: 'อารีย์ (Ari Tufting Studio)',
    rawPrice: '฿1,650',
    rawDescription: 'สัมผัสประสบการณ์ยิงไหมพรมลงผืนผ้าด้วยปืนทัฟติ้ง ออกแบบลายการ์ตูนหรือกราฟิกตามใจ ได้พรมปูห้องนุ่มฟูกลับบ้าน',
    rawImage: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/tufting-rug',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Leather Crafting: เย็บกระเป๋าหนังแท้แฮนด์เมดฉบับช่างฝีมือ',
    rawDate: '18 ต.ค. 2026',
    rawTime: '10:00 - 16:00 น.',
    rawLocation: 'เจริญกรุง (Charoenkrung Leather Craft)',
    rawPrice: '฿2,100',
    rawDescription: 'ตัด เจาะรู และเย็บหนังฟอกฝาดด้วยมือ สร้างสรรค์กระเป๋าสตางค์หรือกระเป๋าใส่บัตร สลักชื่อทองเหลืองสุดประณีต',
    rawImage: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/leather-craft',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Japanese Matcha Ceremony & Whisking Workshop: ศาสตร์แห่งการชงชามัทฉะ',
    rawDate: '1 พ.ย. 2026',
    rawTime: '14:00 - 16:00 น.',
    rawLocation: 'ทองหล่อ (Thonglor Tea House)',
    rawPrice: '฿790',
    rawDescription: 'เรียนรู้วิธีการเลือกผงมัทฉะเกรดพิธีการ อุณหภูมิน้ำ การใช้แปรง Chasen ตีชาให้เกิดโฟมเนียนนุ่ม พร้อมขนมวากาชิโฮมเมด',
    rawImage: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/matcha-ceremony',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Terrarium Moss Garden: จัดสวนขวดแก้วจำลองระบบนิเวศขนาดจิ๋ว',
    rawDate: '15 พ.ย. 2026',
    rawTime: '13:30 - 16:00 น.',
    rawLocation: 'จตุจักร (Chatuchak Plant Sanctuary)',
    rawPrice: '฿690',
    rawDescription: 'จัดวางมอสสด หินธรรมชาติ เฟิร์นจิ๋ว และดินภูเขาไฟลงในโหลแก้วใส เสริมสร้างสมาธิและเพิ่มพื้นที่สีเขียวบนโต๊ะทำงาน',
    rawImage: 'https://images.unsplash.com/photo-1463936575829-25148e1db1b8?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/terrarium-moss',
  },

  // ==========================================
  // ☕ 5. BOARD GAMES, CAFE & SOCIAL MEETUPS (10 Events)
  // ==========================================
  {
    source: 'Eventpop',
    rawTitle: 'Siam Board Game Night: คืนเล่นบอร์ดเกมกระชับมิตรคนรุ่นใหม่',
    rawDate: '5 ก.ย. 2026',
    rawTime: '18:00 - 22:00 น.',
    rawLocation: 'สยามสแควร์ (Siam Board Game Lounge)',
    rawPrice: '฿200',
    rawDescription: 'เปิดตี้บอร์ดเกมวางแผน ปาร์ตี้เกม และบลัฟฟิ่ง เล่นง่าย มี Game Master สอนกติกาละเอียดตั้งแต่เริ่ม มาคนเดียวก็มีเพื่อนเล่นแน่นอน',
    rawImage: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/siam-boardgame-night',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Ari Specialty Coffee Drip & Bean Tasting Cupping Session',
    rawDate: '13 ก.ย. 2026',
    rawTime: '13:00 - 15:30 น.',
    rawLocation: 'อารีย์ (Ari Coffee Roasters Lab)',
    rawPrice: '฿550',
    rawDescription: 'ชิมกาแฟ Specialty Single Origin กว่า 8 แหล่งปลูกทั่วโลก เรียนรู้เทคนิคการดริปกาแฟ การควบคุมอุณหภูมิ และการสกัดรสชาติ',
    rawImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/ari-coffee-cupping',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Bangkok Silent Book Club: นัดอ่านหนังสือเงียบๆ ในคาเฟ่บรรยากาศอบอุ่น',
    rawDate: '20 ก.ย. 2026',
    rawTime: '14:00 - 16:30 น.',
    rawLocation: 'ทองหล่อ (Thonglor Book & Garden Cafe)',
    rawPrice: 'ฟรี!',
    rawDescription: 'พกหนังสือเล่มโปรดมานั่งอ่านอย่างสงบร่วมกับเพื่อนนักอ่าน 1 ชั่วโมง แล้วร่วมแลกเปลี่ยนความประทับใจจิบเครื่องดื่มตามอัธยาศัย',
    rawImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/silent-book-club',
  },
  {
    source: 'SET_Thailand',
    rawTitle: 'SET Young Investor Forum: เสวนาวางแผนการเงินและลงทุนหุ้นคุณค่า',
    rawDate: '26 ก.ย. 2026',
    rawTime: '09:30 - 16:00 น.',
    rawLocation: 'อาคารตลาดหลักทรัพย์แห่งประเทศไทย (SET Building รัชดาภิเษก)',
    rawPrice: 'ฟรี!',
    rawDescription: 'สัมมนาการเงินและการลงทุนหุ้น อสังหาริมทรัพย์ และกองทุนรวม สำหรับคนทำงานรุ่นใหม่ พร้อมเวิร์กช็อปวิเคราะห์งบการเงิน',
    rawImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.set.or.th/event/young-investor-2026',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Rooftop Cinema & Chill Talk: ฉายหนังอินดี้กลางแปลงบนดาดฟ้าเจริญกรุง',
    rawDate: '24 ต.ค. 2026',
    rawTime: '18:30 - 21:30 น.',
    rawLocation: 'เจริญกรุง (Charoenkrung Rooftop Screen)',
    rawPrice: '฿250',
    rawDescription: 'ชมภาพยนตร์คลาสสิกและสารคดีสร้างแรงบันดาลใจบนจอโปรเจกเตอร์ยักษ์ใต้แสงดาว พร้อมป๊อปคอร์นเนยสดและเครื่องดื่มเย็นฉ่ำ',
    rawImage: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/rooftop-cinema',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Bangkok Stand-up Comedy Open Mic: คืนทอล์กโชว์เดี่ยวไมโครโฟนฮากระจาย',
    rawDate: '14 พ.ย. 2026',
    rawTime: '19:30 - 22:00 น.',
    rawLocation: 'สยามสแควร์ (Siam Comedy Club)',
    rawPrice: '฿300',
    rawDescription: 'เวทีเปิดสำหรับคอมเมเดี้ยนหน้าใหม่และรุ่นพี่ ปล่อยมุกชีวิตคนเมือง การทำงาน และความรัก เรียกเสียงหัวเราะคลายเครียดวันหยุด',
    rawImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/comedy-open-mic',
  },

  // ==========================================
  // 🏛️ 6. MAJOR CONVENTIONS & EXPOS (QSNCC, BITEC, IMPACT) (8 Events)
  // ==========================================
  {
    source: 'QSNCC Events',
    rawTitle: 'งานมหกรรมหนังสือระดับชาติ ครั้งที่ 31 (Book Expo Thailand 2026)',
    rawDate: '8 - 19 ต.ค. 2026',
    rawTime: '10:00 - 21:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Exhibition Hall 5-7)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานเทศกาลหนังสือที่ยิ่งใหญ่ที่สุดแห่งปี รวบรวมสำนักพิมพ์กว่า 300 แห่งทั่วประเทศ พร้อมเวทีเสวนานักเขียนชื่อดังและนิทรรศการพิเศษ',
    rawImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.qsncc.com/en/whats-on/event-calendar',
  },
  {
    source: 'QSNCC Events',
    rawTitle: 'Thailand Game Show 2026 (มหกรรมเกมที่ใหญ่ที่สุดในเอเชียตะวันออกเฉียงใต้)',
    rawDate: '23 - 25 ต.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Exhibition Hall 3-4)',
    rawPrice: '฿150',
    rawDescription: 'มหกรรมเกมและเทคโนโลยีความบันเทิงที่ยิ่งใหญ่ที่สุด แข่งขันอีสปอร์ตระดับนานาชาติ คอสเพลย์คอนเทสต์ และเปิดตัวเกมใหม่จากค่ายเกมชั้นนำทั่วโลก',
    rawImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.qsncc.com/en/whats-on/event-calendar',
  },
  {
    source: 'BITEC Events',
    rawTitle: 'Bangkok Comic Con & Pop Culture Expo 2026',
    rawDate: '14 - 15 พ.ย. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Bangna Hall 98-99)',
    rawPrice: '฿200',
    rawDescription: 'งานมหกรรมป๊อปคัลเจอร์ อนิเมะ ของเล่นของสะสม และคอมมูนิตี้คอสเพลย์ที่ใหญ่ที่สุดในกรุงเทพฯ',
    rawImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bitec.co.th/events/bangkok-comic-con-2026',
  },
  {
    source: 'Money Expo',
    rawTitle: 'Money Expo Year-End Bangkok 2026 (มหกรรมการเงินส่งท้ายปี)',
    rawDate: '17 - 20 ธ.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Exhibition Hall 6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานมหกรรมการเงินและการลงทุนส่งท้ายปี รวมโปรโมชั่นสินเชื่อดอกเบี้ยต่ำ ประกันลดหย่อนภาษี และกองทุนรวมเพื่อการออม',
    rawImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://moneyexpo.net/bangkok-year-end-2026',
  },
  {
    source: 'BITEC Events',
    rawTitle: 'Thailand Coffee Tea & Bakery Expo 2027',
    rawDate: '11 - 14 ม.ค. 2027',
    rawTime: '10:00 - 19:00 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Bangna Hall 102)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงสินค้าเครื่องดื่มกาแฟ ชา เบเกอรี่ และไอศกรีมครบวงจร พร้อมการแข่งขันบาริสต้าชิงแชมป์ประเทศไทย',
    rawImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bitec.co.th/events/coffee-expo-2027',
  },
  {
    source: 'BITEC Events',
    rawTitle: 'Bangkok Motor Sale 2027: มหกรรมยานยนต์รับต้นปี',
    rawDate: '20 - 28 ก.พ. 2027',
    rawTime: '11:00 - 21:00 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Bangna Hall 101-105)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงรถยนต์ รถจักรยานยนต์ และยานยนต์ไฟฟ้า EV รุ่นล่าสุด พร้อมข้อเสนอพิเศษส่งตรงจากผู้ผลิต',
    rawImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bitec.co.th/events/motor-sale-2027',
  },
  {
    source: 'QSNCC Events',
    rawTitle: 'Pet Expo Thailand Championship 2026: มหกรรมสัตว์เลี้ยงสุดยิ่งใหญ่',
    rawDate: '29 ต.ค. - 1 พ.ย. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Hall 7-8)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานรวมพลคนรักน้องหมาน้องแมวและสัตว์เลี้ยงแปลก สินค้าลดราคา แข่งขันความสามารถพิเศษ และบริการตรวจสุขภาพสัตว์เลี้ยงฟรี',
    rawImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.qsncc.com/en/whats-on/event-calendar',
  },
  {
    source: 'QSNCC Events',
    rawTitle: 'Architect Expo 2027: งานสถาปนิกและเทคโนโลยีการออกแบบระดับเอเชีย',
    rawDate: '27 เม.ย. - 2 พ.ค. 2027',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Challenger)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานจัดแสดงเทคโนโลยีสถาปัตยกรรม นวัตกรรมวัสดุก่อสร้างสีเขียว และงานออกแบบระดับสากล',
    rawImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.qsncc.com/en/whats-on/event-calendar',
  },

  // ==========================================
  // 🎪 IMPACT EXHIBITIONS & MEGA CONVENTIONS (30 Events)
  // ==========================================
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'HomePro Expo 2026: มหกรรมสินค้าตกแต่งบ้านและเครื่องใช้ไฟฟ้าลดสูงสุด 80%',
    rawDate: '18 ก.ย. - 27 ก.ย. 2026',
    rawTime: '10:00 - 21:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Challenger 1-3)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแฟร์ของแต่งบ้านและเครื่องใช้ไฟฟ้าที่ใหญ่ที่สุด รวมแบรนด์ดังกว่า 500 บูธ พร้อมโปรโมชั่นลดแลกแจกแถมจุใจ',
    rawImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.homepro.co.th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand International Motor Expo 2026: มหกรรมยานยนต์แห่งปี',
    rawDate: '2 ธ.ค. - 13 ธ.ค. 2026',
    rawTime: '12:00 - 22:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Challenger 1-3)',
    rawPrice: '฿100 (แจกบัตรฟรีหน้างาน)',
    rawDescription: 'งานแสดงรถยนต์ รถจักรยานยนต์ และนวัตกรรมยานยนต์ไฟฟ้า EV รุ่นล่าสุดจากทุกค่ายชั้นนำระดับโลก',
    rawImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.motorexpo.co.th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'OTOP City 2026: มหกรรมของดีและหัตถศิลป์ไทยระดับ 5 ดาว',
    rawDate: '12 ธ.ค. - 20 ธ.ค. 2026',
    rawTime: '10:00 - 21:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 9-12)',
    rawPrice: 'ฟรี!',
    rawDescription: 'รวบรวมสุดยอดสินค้าหนึ่งตำบลหนึ่งผลิตภัณฑ์ ผ้าไหมไทย อาหารพื้นถิ่น และงานฝีมือจาก 77 จังหวัดทั่วไทย',
    rawImage: 'https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.cdd.go.th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand Coffee, Tea & Drinks 2026 @ IMPACT',
    rawDate: '15 ต.ค. - 18 ต.ค. 2026',
    rawTime: '10:00 - 19:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 5-6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงนวัตกรรมชา กาแฟ เบเกอรี่ และเครื่องดื่มครบวงจรสำหรับผู้ประกอบการและคอกาแฟตัวจริง',
    rawImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.thailandcoffee.net',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Japan Anime & Cosplay Fest Bangkok 2026',
    rawDate: '24 ต.ค. - 25 ต.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Arena & Hall 7)',
    rawPrice: '฿150',
    rawDescription: 'เทศกาลแฟนมีตคอสเพลย์ การประกวดเต้น Cover Dance สินค้าการ์ตูนอนิเมะ และคอนเสิร์ตเพลงการ์ตูนญี่ปุ่นสุดอลังการ',
    rawImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Bangkok International Motor Show (BIMS 2027)',
    rawDate: '24 มี.ค. - 04 เม.ย. 2027',
    rawTime: '11:00 - 22:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Challenger 1-3)',
    rawPrice: '฿100',
    rawDescription: 'งานบางกอก อินเตอร์เนชั่นแนล มอเตอร์โชว์ ครั้งยิ่งใหญ่ที่สุดในเอเชียตะวันออกเฉียงใต้ นวัตกรรม Supercar และ EV Concept Car',
    rawImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.motorshow.in.th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thaifex - Anuga Asia: มหกรรมอาหารและเครื่องดื่มระดับโลก',
    rawDate: '25 พ.ค. - 29 พ.ค. 2027',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Challenger & Exhibition Hall 5-12)',
    rawPrice: 'ฟรี (ลงทะเบียนล่วงหน้า)',
    rawDescription: 'งานแสดงสินค้าอาหารและเครื่องดื่มที่ใหญ่ที่สุดในเอเชีย ครอบคลุม Future Food เทคโนโลยีแปรรูปอาหารและนวัตกรรมเครื่องดื่ม',
    rawImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://thaifex-anuga.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand Baby & Kids Best Buy Expo (BBB 2026)',
    rawDate: '8 ต.ค. - 11 ต.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Challenger Hall 3)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานมหกรรมสินค้าแม่และเด็กอันดับ 1 ของไทย รวบรวมเสื้อผ้า รถเข็น คาร์ซีท และของเล่นเสริมพัฒนาการลดสูงสุด 70%',
    rawImage: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.babykid-bestbuy.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Smart City Expo Thailand: นวัตกรรมเมืองอัจฉริยะและเทคโนโลยี 5G',
    rawDate: '4 พ.ย. - 6 พ.ย. 2026',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'การประชุมและนิทรรศการเมืองอัจฉริยะ นวัตกรรม IoT, AI, พลังงานสะอาด และโซลูชันสิ่งแวดล้อมเพื่อการอยู่อาศัยยุคใหม่',
    rawImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.thailandsmartcityexpo.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Pet Variety Fest: มหกรรมการแข่งขันและรวมพลสัตว์เลี้ยงแสนรัก',
    rawDate: '1 ต.ค. - 4 ต.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 7-8)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานประกวดสุนัข แมว นก และ Exotic Pets พร้อมโซนตรวจสุขภาพสัตว์เลี้ยงฟรี กิจกรรมวิ่งแข่งชิงรางวัล และช้อปปิ้งของใช้ลดราคา',
    rawImage: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Bangkok Wedding Fair of the Year 2026',
    rawDate: '17 ต.ค. - 25 ต.ค. 2026',
    rawTime: '10:30 - 20:30 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 9-10)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานเวดดิ้งแฟร์ครบวงจร รวมสตูดิโอถ่ายภาพ ชุดแต่งงาน แหวนเพชร และแพ็กเกจโรงแรมจัดเลี้ยงชั้นนำพร้อมโปรโมชั่นพิเศษ',
    rawImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand Furniture Showroom Grand Sale 2026',
    rawDate: '7 พ.ย. - 15 พ.ย. 2026',
    rawTime: '10:30 - 21:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 9-11)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงเฟอร์นิเจอร์โรงงานผู้ผลิต โซฟาหนังแท้ เตียงนอนไม้สัก โต๊ะอาหาร และของแต่งบ้านสไตล์มินิมอลราคาส่ง',
    rawImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Cosmoprof CBE ASEAN: มหกรรมความงามและเครื่องสำอางนานาชาติ',
    rawDate: '11 มิ.ย. - 13 มิ.ย. 2027',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 9-12)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานเจรจาธุรกิจความงามระดับโลก รวบรวมแบรนด์สกินแคร์ เครื่องสำอาง สปา และแพ็กเกจจิ้งจากทั่วโลกกว่า 1,000 แบรนด์',
    rawImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.cosmoprofcbeasean.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'DigiTech ASEAN Thailand: AI, Cyber Security & Big Data Expo',
    rawDate: '18 พ.ย. - 20 พ.ย. 2026',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 5-6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงเทคโนโลยีดิจิทัล ปัญญาประดิษฐ์ (AI) คลาวด์คอมพิวติ้ง และระบบความปลอดภัยไซเบอร์สำหรับองค์กรธุรกิจ',
    rawImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://digitechasean.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand International Franchise & Business Opportunities (TFBO)',
    rawDate: '16 ก.ค. - 19 ก.ค. 2026',
    rawTime: '10:00 - 19:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 7-8)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงธุรกิจแฟรนไชส์ที่ใหญ่ที่สุดในอาเซียน รวมแฟรนไชส์ร้านอาหาร คาเฟ่ ขนส่ง และธุรกิจบริการกว่า 300 แบรนด์',
    rawImage: 'https://images.unsplash.com/photo-1556742049-0a67e557b6f6?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.thailandfranchising.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand Retail, Food & Hospitality Services (TRAFS 2026)',
    rawDate: '16 ก.ค. - 19 ก.ค. 2026',
    rawTime: '10:00 - 19:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 6-7)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงอุปกรณ์เครื่องใช้ วัตถุดิบ และโซลูชันสำหรับโรงแรม ร้านอาหาร เบเกอรี่ และธุรกิจบริการอาหารครบวงจร',
    rawImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.trafs.net',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand Toy & Designer Art Toys Expo @ IMPACT',
    rawDate: '29 ส.ค. - 30 ส.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Forum Hall 4)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานรวมพลคนรักของเล่น อาร์ตทอย กล่องสุ่ม ฟิกเกอร์ลิมิเต็ด และผลงานของศิลปินนักออกแบบรุ่นใหม่จากทั่วเอเชีย',
    rawImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'ProPak Asia: งานแสดงสินค้าและนวัตกรรมแปรรูปบรรจุภัณฑ์ระดับเอเชีย',
    rawDate: '16 มิ.ย. - 19 มิ.ย. 2027',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 9-12)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงสินค้าอุตสาหกรรมแปรรูปและบรรจุภัณฑ์อาหาร เครื่องดื่ม เภสัชกรรม และสินค้าอุปโภคบริโภคที่ใหญ่ที่สุดในเอเชีย',
    rawImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.propakasia.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Thailand Halal Assembly: การประชุมวิชาการและงานแสดงสินค้าฮาลาลนานาชาติ',
    rawDate: '3 ธ.ค. - 5 ธ.ค. 2026',
    rawTime: '10:00 - 19:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'การประชุมวิชาการด้านวิทยาศาสตร์ฮาลาลและมหกรรมสินค้า อาหาร แฟชั่น และการท่องเที่ยวฮาลาลระดับสากล',
    rawImage: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://thailandhalalassembly.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Green Energy & EV Mobility Technology Expo 2026',
    rawDate: '10 ก.ย. - 12 ก.ย. 2026',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Exhibition Hall 5)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงนวัตกรรมพลังงานสะอาด โซลาร์เซลล์ ระบบกักเก็บพลังงานแบตเตอรี่ และเทคโนโลยีสถานีชาร์จยานยนต์ไฟฟ้า EV',
    rawImage: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'National Science & Technology Fair 2026 (มหกรรมวิทยาศาสตร์แห่งชาติ)',
    rawDate: '15 ส.ค. - 23 ส.ค. 2026',
    rawTime: '09:00 - 19:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Challenger 2)',
    rawPrice: 'ฟรี!',
    rawDescription: 'มหกรรมวิทยาศาสตร์และเทคโนโลยีที่ใหญ่ที่สุดของไทย การทดลองทางวิทยาศาสตร์ หุ่นยนต์ AI อวกาศ และกิจกรรม Interactive',
    rawImage: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.nsm.or.th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Building Construction Technology Expo (BCT Expo 2026)',
    rawDate: '23 ก.ย. - 25 ก.ย. 2026',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 8)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงสินค้าเทคโนโลยีอาคารและการก่อสร้าง เครื่องจักรกลหนัก วัสดุโครงสร้าง และระบบบริหารจัดการอาคารอัจฉริยะ',
    rawImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'LED Expo Thailand + Smart Light ASEAN 2026',
    rawDate: '10 ก.ย. - 12 ก.ย. 2026',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 7)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงนวัตกรรมหลอดไฟ LED ระบบไฟส่องสว่างอัจฉริยะ และแสงไฟสถาปัตยกรรมเพื่อการประหยัดพลังงานในระดับอาเซียน',
    rawImage: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.ledexpothailand.com',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Medical Fair Thailand: งานแสดงเครื่องมือและเทคโนโลยีทางการแพทย์',
    rawDate: '8 ก.ย. - 10 ก.ย. 2027',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 9-11)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงอุปกรณ์ทางการแพทย์ นวัตกรรมดิจิทัลเฮลท์แคร์ และระบบการดูแลสุขภาพที่ใหญ่ที่สุดในภูมิภาค',
    rawImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'SIMA ASEAN Thailand: งานแสดงเครื่องจักรกลการเกษตรระดับภูมิภาค',
    rawDate: '17 ก.ย. - 19 ก.ย. 2026',
    rawTime: '10:00 - 18:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 5-6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานแสดงเทคโนโลยีการเกษตรแม่นยำ รถแทรกเตอร์ โดรนเพื่อการเกษตร และอุปกรณ์ระบบน้ำอัจฉริยะ',
    rawImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.impact.co.th/index.php/visitor/event/th',
  },
  {
    source: 'IMPACT Exhibition',
    rawTitle: 'Bangkok Indie Live Music Hall @ IMPACT Forum',
    rawDate: '31 ต.ค. 2026',
    rawTime: '17:00 - 23:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Forum Hall 4)',
    rawPrice: '฿800',
    rawDescription: 'คอนเสิร์ตวงดนตรีอินดี้ป็อปและร็อกรุ่นใหม่ 8 วงดัง แสงสีเสียงจัดเต็มในฮอลล์ปรับอากาศสุดสบาย',
    rawImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.theconcert.com',
  },

  // ==========================================
  // ⏪ 7. PAST ARCHIVE EVENTS (Last 60 Days - June & July 2026) (5 Events)
  // ==========================================
  {
    source: 'ThaiRun',
    rawTitle: 'Bangkok Pride Marathon 2026 (งานที่ผ่านมา)',
    rawDate: '28 มิ.ย. 2026',
    rawTime: '05:00 - 09:00 น.',
    rawLocation: 'สยามสแควร์ - สวนลุมพินี (Siam to Lumpini)',
    rawPrice: '฿500',
    rawDescription: 'งานวิ่งเฉลิมฉลอง Pride Month ที่รวมนักวิ่งกว่า 5,000 คนบนถนนพระราม 1 (จัดเสร็จสิ้นแล้ว สามารถเขียนรีวิวและสะสมแต้ม XP ย้อนหลังได้)',
    rawImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/pride2026',
  },
  {
    source: 'BMA Events',
    rawTitle: 'BMA Music in the Garden: ดนตรีในสวนเบญจกิติ (งานที่ผ่านมา)',
    rawDate: '12 ก.ค. 2026',
    rawTime: '16:30 - 19:30 น.',
    rawLocation: 'สวนเบญจกิติ (Benchakitti Forest Park)',
    rawPrice: 'ฟรี!',
    rawDescription: 'เทศกาลดนตรีในสวนกลางกรุง จัดโดยกรุงเทพมหานคร บรรยากาศสุดผ่อนคลาย (จัดเสร็จสิ้นแล้ว สมาชิกสามารถเขียนรีวิวได้)',
    rawImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://pr-bangkok.com/music-in-park-july',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Bangkok Coffee Fest Mid-Year 2026 (งานที่ผ่านมา)',
    rawDate: '18 ก.ค. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'อิมแพ็ค เมืองทองธานี (IMPACT Hall 5-6)',
    rawPrice: 'ฟรี!',
    rawDescription: 'มหกรรมกาแฟกลางปีที่ใหญ่ที่สุด รวมโรงคั่วกาแฟและบาริสต้าชั้นนำกว่า 200 แบรนด์ (จัดเสร็จสิ้นแล้ว)',
    rawImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/coffee-fest-july',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Suan Rot Fai Morning 10K Challenge (งานที่ผ่านมา)',
    rawDate: '26 ก.ค. 2026',
    rawTime: '05:30 - 08:30 น.',
    rawLocation: 'สวนวชิรเบญจทัศ (สวนรถไฟ จตุจักร)',
    rawPrice: '฿350',
    rawDescription: 'งานวิ่งมินิมาราธอนรับอรุณท่ามกลางร่มเงาไม้ใหญ่ สวนรถไฟ (จัดเสร็จสิ้นแล้ว)',
    rawImage: 'https://images.unsplash.com/photo-1486218119243-13883505764c?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/rotfai-july',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Ari Creative Market & Flea: ตลาดนัดงานคราฟต์อารีย์ (งานที่ผ่านมา)',
    rawDate: '2 ส.ค. 2026',
    rawTime: '11:00 - 20:00 น.',
    rawLocation: 'อารีย์ (Ari Craft Yard)',
    rawPrice: 'ฟรี!',
    rawDescription: 'ตลาดนัดสินค้าแฮนด์เมด เซรามิก เสื้อผ้ามือสอง และกาแฟคราฟต์สุดชิคย่านอารีย์ (จัดเสร็จสิ้นแล้ว)',
    rawImage: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/ari-craft-august',
  },
];

export async function fetchLiveRawEvents(): Promise<ScrapedRawEvent[]> {
  // Simulate network scrape delay
  await new Promise((resolve) => setTimeout(resolve, 600));
  return REAL_BANGKOK_EVENT_SEEDS;
}
