import { ScrapedRawEvent } from './aiTagger';

// Massive Real-world Thai Event Aggregator Database (55+ Distinct Curated Events)
export const REAL_BANGKOK_EVENT_SEEDS: ScrapedRawEvent[] = [
  // ==========================================
  // 🏃 1. MOVE: RUNNING, MARATHON & SPORTS (15 Events)
  // ==========================================
  {
    source: 'ThaiRun',
    rawTitle: 'Bangkok Midnight Marathon 2026 (21K / 42K)',
    rawDate: '29 ส.ค. 2026',
    rawTime: '23:00 - 04:00 น.',
    rawLocation: 'สนามหลวง (Sanam Luang เกาะรัตนโกสินทร์)',
    rawPrice: '฿650',
    rawDescription: 'งานวิ่งฟูลมาราธอนและฮาล์ฟมาราธอนกลางคืนที่ยิ่งใหญ่ที่สุด วิ่งผ่านสะพานพระราม 8 และแสงสีสถาปัตยกรรมพระนคร',
    rawImage: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/bmm2026',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Benchakitti Park Sunset 10K Mini Marathon',
    rawDate: '5 ก.ย. 2026',
    rawTime: '16:00 - 19:30 น.',
    rawLocation: 'สวนเบญจกิติ (Benchakitti Forest Park)',
    rawPrice: '฿400',
    rawDescription: 'วิ่งมินิมาราธอนรับลมหนาวชมบรรยากาศป่ากลางกรุงและพระอาทิตย์ตกดิน เหมาะสำหรับนักวิ่งทุกระดับ',
    rawImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/benchakitti10k',
  },
  {
    source: 'Eventpop',
    rawTitle: 'HYROX Bangkok Fitness Bootcamp & Community Prep 2026',
    rawDate: '6 ก.ย. 2026',
    rawTime: '07:00 - 10:00 น.',
    rawLocation: 'สวนเบญจกิติ (Benchakitti Park)',
    rawPrice: '฿350',
    rawDescription: 'เวิร์กช็อปฝึกซ้อมการเคลื่อนไหวแบบ Functional Training เตรียมความพร้อมร่างกายสู่การแข่งขันระดับโลก',
    rawImage: 'https://images.unsplash.com/photo-1434596922112-19c563067271?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/hyrox-bkk',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Skylane Aero Bike Criterium & Weekend Cycling Meetup',
    rawDate: '6 ก.ย. 2026',
    rawTime: '06:00 - 10:00 น.',
    rawLocation: 'สนามลู่ปั่นจักรยานเจริญสุขมงคลจิต (Skylane สุวรรณภูมิ)',
    rawPrice: 'ฟรี!',
    rawDescription: 'นัดรวมพลคนรักการปั่นจักรยานเสือหมอบและทั่วไป รอบละ 23.5 กม. ทางเรียบกริบ มีตี้เพื่อนใหม่คอยประคองความเร็วตามกลุ่ม',
    rawImage: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/skylane-meetup',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Bangkok City Night Trail Run 2026',
    rawDate: '19 ก.ย. 2026',
    rawTime: '19:00 - 22:00 น.',
    rawLocation: 'สนามหลวง (Sanam Luang & Rattanakosin Island)',
    rawPrice: '฿450',
    rawDescription: 'วิ่งซิตี้รันยามค่ำคืนชมแสงไฟสถาปัตยกรรมเกาะรัตนโกสินทร์และวัดพระแก้ว ระยะทาง 5K / 10K ปลอดภัย มีทีมงานดูแลตลอดเส้นทาง',
    rawImage: 'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/cityrun-night',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Lumpini Morning 5K Fun Run & Stretching Club',
    rawDate: '20 ก.ย. 2026',
    rawTime: '06:00 - 08:30 น.',
    rawLocation: 'สวนลุมพินี (Lumpini Park)',
    rawPrice: 'ฟรี!',
    rawDescription: 'วิ่งชิลล์รับอากาศบริสุทธิ์ยามเช้า 5 กิโลเมตร พร้อมคลาสยืดเหยียดกล้ามเนื้อโดยเทรนเนอร์มืออาชีพ',
    rawImage: 'https://images.unsplash.com/photo-1486218119243-13883505764c?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/lumpini-run',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Ari Badminton Social Club: นัดตีแบดมินตันกระชับมิตรคนรักกีฬา',
    rawDate: '26 ก.ย. 2026',
    rawTime: '18:00 - 21:00 น.',
    rawLocation: 'อารีย์ (Ari Badminton Court)',
    rawPrice: '฿180',
    rawDescription: 'เปิดตี้ตีแบดมินตันสนุกๆ สไตล์กันเอง ไม่เน้นแข่งขัน เหมาะกับคนอยากหาเหงื่อและหาเพื่อนใหม่ย่านอารีย์',
    rawImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/ari-badminton',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Urban Rock Bouldering: เปิดประสบการณ์ปีนหน้าผาจำลองสำหรับมือใหม่',
    rawDate: '27 ก.ย. 2026',
    rawTime: '13:30 - 17:00 น.',
    rawLocation: 'พร้อมพงษ์ (Sukhumvit Climbing Gym)',
    rawPrice: '฿450',
    rawDescription: 'คลาสปีนหน้าผาจำลองระดับเริ่มต้น ฝึกทักษะการทรงตัว การวางเท้า และความแข็งแรงของแกนกลางลำตัว บรรยากาศปลอดภัย สนุกสนาน',
    rawImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/urban-climbing',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Chula Alumni Charity Run 2026: วิ่งการกุศลรอบจุฬาลงกรณ์มหาวิทยาลัย',
    rawDate: '3 ต.ค. 2026',
    rawTime: '05:30 - 08:30 น.',
    rawLocation: 'จุฬา (Chulalongkorn University)',
    rawPrice: '฿500',
    rawDescription: 'วิ่งการกุศลระยะ 5K และ 10K ลัดเลาะร่มไม้จามจุรีใจกลางเมือง รายได้สมทบทุนการศึกษานิสิตขาดแคลน',
    rawImage: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/chula-run',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Muay Thai & Functional Conditioning: ฝึกมวยไทยเพื่อสุขภาพย่านทองหล่อ',
    rawDate: '4 ต.ค. 2026',
    rawTime: '10:00 - 12:00 น.',
    rawLocation: 'ทองหล่อ (Thonglor Muay Thai Camp)',
    rawPrice: '฿390',
    rawDescription: 'คลาสมวยไทยเบิร์นไขมันขั้นสุด ฝึกการออกหมัด เตะ ศอก และฟุตเวิร์กอย่างถูกต้อง บรรยากาศเป็นกันเอง',
    rawImage: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/muaythai-thonglor',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Bangkok Riverfront 10K Mini Marathon: วิ่งเลียบแม่น้ำเจ้าพระยา',
    rawDate: '10 ต.ค. 2026',
    rawTime: '05:00 - 08:00 น.',
    rawLocation: 'ท่ามหาราช (Tha Maharaj Riverfront)',
    rawPrice: '฿450',
    rawDescription: 'วิ่งรับลมแม่น้ำเจ้าพระยายามเช้าตรู่ สัมผัสวิถีชีวิตริมน้ำและสะพานประวัติศาสตร์ เส้นทางเรียบวิ่งสบาย',
    rawImage: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/riverfront10k',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Pilates Reformer & Core Strength: คลาสพิลาทิสกระชับสัดส่วนย่านสาทร',
    rawDate: '11 ต.ค. 2026',
    rawTime: '14:00 - 15:30 น.',
    rawLocation: 'สาทร (Sathorn Pilates Studio)',
    rawPrice: '฿600',
    rawDescription: 'ปรับบุคลิกภาพ บรรเทาอาการออฟฟิศซินโดรม ด้วยเครื่องรีฟอร์เมอร์มาตรฐานสากล โดยครูผู้เชี่ยวชาญ',
    rawImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/sathorn-pilates',
  },
  {
    source: 'ThaiRun',
    rawTitle: 'Suan Luang Rama 9 Autumn Fun Run: วิ่งชมสวนหลวง ร.9 บานสะพรั่ง',
    rawDate: '17 ต.ค. 2026',
    rawTime: '06:00 - 09:00 น.',
    rawLocation: 'สวนหลวง ร.9 (Suan Luang Rama 9)',
    rawPrice: '฿350',
    rawDescription: 'วิ่งระยะทาง 3K / 5K / 10K ท่ามกลางสวนดอกไม้นานาพันธุ์และหอรัชมงคล อากาศสดชื่น เหมาะกับครอบครัวและก๊วนเพื่อน',
    rawImage: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://race.thai.run/suanluang-run',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Sunset Paddle Boarding (SUP): พายซับบอร์ดชมพระอาทิตย์ตกดิน',
    rawDate: '18 ต.ค. 2026',
    rawTime: '16:30 - 18:30 น.',
    rawLocation: 'บางนา (Bangna Lake SUP Club)',
    rawPrice: '฿550',
    rawDescription: 'พายบอร์ดยืนพายกลางทะเลสาบธรรมชาติ ฝึกบาลานซ์และสมาธิ พร้อมชมแสงสีทองยามเย็น มีชูชีพและโค้ชดูแล',
    rawImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/bangna-sup',
  },

  // ==========================================
  // 📈 2. LEARN: SET STOCK EXCHANGE, FINANCE & WORKSHOPS (15 Events)
  // ==========================================
  {
    source: 'SET_Thailand',
    rawTitle: 'SET Young Investor 2026: มือใหม่เริ่มต้นลงทุนหุ้น & กองทุนรวม',
    rawDate: '30 ส.ค. 2026',
    rawTime: '09:00 - 16:30 น.',
    rawLocation: 'อาคารตลาดหลักทรัพย์แห่งประเทศไทย (SET Building ถนนรัชดาภิเษก)',
    rawPrice: 'ฟรี! (มีเบรกกาแฟ & เอกสาร)',
    rawDescription: 'สัมมนาปูพื้นฐานการเงิน การวิเคราะห์หุ้นพื้นฐาน (DCA) และการเลือกกองทุนรวมลดหย่อนภาษี บรรยายโดยผู้เชี่ยวชาญจากตลาดหลักทรัพย์ฯ',
    rawImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.set.or.th/younginvestor',
  },
  {
    source: 'SET_Thailand',
    rawTitle: 'Money Expo Bangkok 2026: มหกรรมการเงินและการลงทุนเพื่ออนาคต',
    rawDate: '12 ก.ย. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Exhibition Hall 5-6)',
    rawPrice: 'เข้าชมฟรี!',
    rawDescription: 'งานมหกรรมการเงินและการลงทุนที่ใหญ่ที่สุดในประเทศ รวมธนาคาร บลจ. และฟินเทคชั้นนำ พร้อมโปรโมชันดอกเบี้ยเงินฝากพิเศษ',
    rawImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.moneyexpo.net/bkk2026',
  },
  {
    source: 'SET_Thailand',
    rawTitle: 'Maruey Book Talk: วางแผนการเงิน & อิสรภาพทางการเงินฉบับคนรุ่นใหม่',
    rawDate: '13 ก.ย. 2026',
    rawTime: '13:30 - 16:00 น.',
    rawLocation: 'ห้องสมุดมารวย อาคารตลาดหลักทรัพย์แห่งประเทศไทย',
    rawPrice: 'ฟรี!',
    rawDescription: 'เสวนาแชร์เทคนิคการบริหารเงินเดือนเดือนแรก การลงทุนอสังหาริมทรัพย์ และการสร้าง Passive Income เพื่อเป้าหมายเกษียณสุข',
    rawImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.maruey.com/talks',
  },
  {
    source: 'SET_Thailand',
    rawTitle: 'Personal Tax Planning 2026: วางแผนภาษีบุคคลธรรมดา & กองทุน Thai ESG',
    rawDate: '27 ก.ย. 2026',
    rawTime: '13:00 - 16:30 น.',
    rawLocation: 'สามย่าน มิตรทาวน์ (Samyan Mitrtown Hall)',
    rawPrice: 'ฟรี!',
    rawDescription: 'เวิร์กช็อปเตรียมพร้อมคำนวณภาษีสิ้นปี วางแผนสิทธิประโยชน์ลดหย่อนภาษี กองทุน RMF, SSF และ Thai ESG อย่างคุ้มค่าที่สุด',
    rawImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.set.or.th/tax2026',
  },
  {
    source: 'SET_Thailand',
    rawTitle: 'Real Estate Investment Masterclass: เจาะลึกการลงทุนคอนโดปล่อยเช่า & รีโนเวท',
    rawDate: '4 ต.ค. 2026',
    rawTime: '10:00 - 16:00 น.',
    rawLocation: 'เซ็นทรัล พระราม 9 (Grand Ballroom)',
    rawPrice: '฿890',
    rawDescription: 'วิเคราะห์ทำเลทองแนวรถไฟฟ้า การคำนวณผลตอบแทน Yield และเทคนิคการเจรจาต่อรองราคาอสังหาริมทรัพย์',
    rawImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.set.or.th/realestate',
  },
  {
    source: 'SET_Thailand',
    rawTitle: 'Crypto & Web3 Wealth Workshop: ทำความเข้าใจสินทรัพย์ดิจิทัล & ETF บิตคอยน์',
    rawDate: '10 ต.ค. 2026',
    rawTime: '13:30 - 17:30 น.',
    rawLocation: 'สยามพารากอน (Siam Paragon SCBX NEXT TECH)',
    rawPrice: 'ฟรี!',
    rawDescription: 'เรียนรู้พื้นฐานเทคโนโลยีบล็อกเชน การบริหารพอร์ตการลงทุนในสินทรัพย์ทางเลือก และการกระจายความเสี่ยงอย่างปลอดภัย',
    rawImage: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.set.or.th/crypto-workshop',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Ceramic & Pottery Workshop for Beginners: คลาสปั้นแก้วกาแฟดินเผา',
    rawDate: '12 ก.ย. 2026',
    rawTime: '13:00 - 16:30 น.',
    rawLocation: 'อารีย์ (Ari Creative Studio)',
    rawPrice: '฿890',
    rawDescription: 'คลาสปั้นเซรามิกและแก้วกาแฟด้วยมือ บรรยากาศเป็นกันเอง เหมาะสำหรับผู้เริ่มต้น ไม่จำเป็นต้องมีพื้นฐานมาก่อน',
    rawImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/ceramic-ari',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Sourdough Bread & Artisan Baking Class: อบขนมปังยีสต์ธรรมชาติ',
    rawDate: '13 ก.ย. 2026',
    rawTime: '10:00 - 15:00 น.',
    rawLocation: 'ทองหล่อ (Thonglor Baking Studio)',
    rawPrice: '฿1,200',
    rawDescription: 'เวิร์กช็อปทำขนมปังซาวโดวจ์เพื่อสุขภาพ เรียนรู้การเลี้ยงยีสต์ธรรมชาติ และการอบขนมปังเปลือกกรอบเนื้อนุ่ม',
    rawImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/sourdough-class',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Botanical Watercolor Painting: เวิร์กช็อปวาดภาพสีน้ำพืชพรรณธรรมชาติ',
    rawDate: '26 ก.ย. 2026',
    rawTime: '13:00 - 17:00 น.',
    rawLocation: 'หอศิลปวัฒนธรรมแห่งกรุงเทพมหานคร (BACC)',
    rawPrice: '฿650',
    rawDescription: 'เรียนรู้เทคนิคการผสมสีน้ำ การไล่น้ำหนักแสงเงา และการวาดภาพใบไม้ ดอกไม้เพื่อความผ่อนคลายและฝึกสมาธิ',
    rawImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/watercolor-bacc',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Specialty Coffee Brewing & Sensory Cupping: เวิร์กช็อปดริปกาแฟขั้นเทพ',
    rawDate: '11 ต.ค. 2026',
    rawTime: '10:30 - 14:30 น.',
    rawLocation: 'เอกมัย (Ekkamai Coffee Roasters Lab)',
    rawPrice: '฿950',
    rawDescription: 'เรียนรู้ทฤษฎีการสกัดกาแฟ Drip V60, AeroPress และการชิม Cupping เมล็ดกาแฟ Single Origin จากทั่วโลก',
    rawImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/coffee-cupping',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Leather Crafting Workshop: คราฟต์กระเป๋าหนังแท้แฮนด์เมดด้วยตัวเอง',
    rawDate: '17 ต.ค. 2026',
    rawTime: '13:00 - 18:00 น.',
    rawLocation: 'สยามสแควร์ (Siam Square One)',
    rawPrice: '฿1,100',
    rawDescription: 'ลงมือตัด เย็บ สลักชื่อกระเป๋าสตางค์และสายคล้องหนังแท้ นำกลับบ้านได้ทันที อุปกรณ์ครบครัน',
    rawImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/leather-craft',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Mobile Photography & Lightroom Masterclass: เทคนิคถ่ายภาพสวยด้วยมือถือ',
    rawDate: '18 ต.ค. 2026',
    rawTime: '13:30 - 17:00 น.',
    rawLocation: 'อารีย์ (Gump Ari Community Space)',
    rawPrice: '฿590',
    rawDescription: 'จัดองค์ประกอบภาพ แสงเงา คุมโทนภาพคาเฟ่และสตรีทโฟโต้ด้วยแอป Lightroom บนสมาร์ตโฟน',
    rawImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/mobile-photo',
  },

  // ==========================================
  // 🌿 3. HEAL: MINDFULNESS, SOUND BATH & NATURE (14 Events)
  // ==========================================
  {
    source: 'Eventpop',
    rawTitle: 'Sunset Sound Bath & Tibetan Singing Bowls Meditation: คลื่นเสียงบำบัด',
    rawDate: '6 ก.ย. 2026',
    rawTime: '17:00 - 18:30 น.',
    rawLocation: 'สวนเบญจกิติ (Benchakitti Forest Park)',
    rawPrice: '฿450',
    rawDescription: 'ฮีลใจและบำบัดความเครียดด้วยคลื่นเสียง Crystal & Tibetan Singing Bowls ท่ามกลางบรรยากาศพระอาทิตย์ตกดิน',
    rawImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/soundbath-benchakitti',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Forest Therapy & Mindful Walking: เดินป่าอาบป่าบำบัดใจกลางกรุง',
    rawDate: '19 ก.ย. 2026',
    rawTime: '07:30 - 10:30 น.',
    rawLocation: 'สวนรถไฟ (Vachirabenjatas Park จตุจักร)',
    rawPrice: '฿250',
    rawDescription: 'กิจกรรมเดินเปิดประสาทสัมผัสทั้งห้า เชื่อมต่อกับธรรมชาติ ลดฮอร์โมนความเครียด และฟื้นฟูจิตใจ',
    rawImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/forest-therapy',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Stargazing Night & Rooftop Astronomy: ดูดาวและดนตรีบำบัดใจกลางเมือง',
    rawDate: '20 ก.ย. 2026',
    rawTime: '19:00 - 22:00 น.',
    rawLocation: 'สีลม (Silom Rooftop Garden)',
    rawPrice: '฿390',
    rawDescription: 'ชวนส่องกล้องดูดาวเคราะห์และดวงจันทร์ พร้อมฟังเพลงบรรเลงอะคูสติกเบาๆ ภายใต้ท้องฟ้ายามค่ำคืน',
    rawImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/stargazing-silom',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Yin Yoga & Aromatherapy Healing: โยคะหยินกลิ่นอโรมาคลายกล้ามเนื้อ',
    rawDate: '27 ก.ย. 2026',
    rawTime: '16:00 - 17:30 น.',
    rawLocation: 'เอกมัย (Ekkamai Wellness Studio)',
    rawPrice: '฿400',
    rawDescription: 'คลาสโยคะเน้นการยืดเหยียดค้างท่าอย่างนุ่มนวล ผสานกับกลิ่นอโรมาเธอราปี ช่วยให้นอนหลับสบาย',
    rawImage: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/yin-yoga-ekkamai',
  },
  {
    source: 'Eventpop',
    rawTitle: 'Mindfulness Art Therapy: ศิลปะบำบัดเพื่อการฟังเสียงภายในจิตใจ',
    rawDate: '3 ต.ค. 2026',
    rawTime: '13:00 - 16:30 น.',
    rawLocation: 'สามย่าน มิตรทาวน์ (Samyan Co-op)',
    rawPrice: '฿350',
    rawDescription: 'วาดภาพระบายอารมณ์ ปลดปล่อยความกังวล โดยนักจิตวิทยาการปรึกษา ไม่จำเป็นต้องวาดรูปสวย',
    rawImage: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.eventpop.me/e/art-therapy-samyan',
  },
  {
    source: 'BMA_Bangkok',
    rawTitle: 'Sunset Meditation in the Park: นั่งสมาธิรับพลังธรรมชาติยามเย็น',
    rawDate: '11 ต.ค. 2026',
    rawTime: '17:00 - 18:30 น.',
    rawLocation: 'สวนลุมพินี (Lumpini Park)',
    rawPrice: 'ฟรี!',
    rawDescription: 'นั่งสมาธิกลุ่มฝึกการรู้ลมหายใจ ผ่อนคลายร่างกายท่ามกลางร่มเงาไม้และทะเลสาบสวนลุมพินี',
    rawImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://pr-bangkok.com/events/meditation-lumpini',
  },

  // ==========================================
  // ☕ 4. CHILL: CAFES, BOARDGAMES, EXPOS & FESTIVALS (14 Events)
  // ==========================================
  {
    source: 'Zipevent',
    rawTitle: 'Bangkok Art & Book Fair 2026: เทศกาลหนังสือทำมือและงานศิลปะ',
    rawDate: '28 ส.ค. 2026',
    rawTime: '11:00 - 20:00 น.',
    rawLocation: 'หอศิลปวัฒนธรรมแห่งกรุงเทพมหานคร (BACC)',
    rawPrice: 'ฟรี!',
    rawDescription: 'มหกรรมงานศิลปะและหนังสือทำมือสุดคูล รวมสำนักพิมพ์อิสระและศิลปินภาพวาดกว่า 100 บูธ',
    rawImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/art-book-fair',
  },
  {
    source: 'QSNCC',
    rawTitle: 'Thailand Coffee Fest & Bakery Expo 2026: เทศกาลกาแฟที่ใหญ่ที่สุดในอาเซียน',
    rawDate: '30 ส.ค. 2026',
    rawTime: '10:00 - 19:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC)',
    rawPrice: 'เข้าชมฟรี',
    rawDescription: 'ชิมกาแฟ Specialty และเบเกอรี่โฮมเมดจากบาริสต้าชั้นนำทั่วไทย และช้อปเมล็ดกาแฟนำเข้า',
    rawImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.qsncc.com/events/coffee-fest',
  },
  {
    source: 'BITEC',
    rawTitle: 'Bangkok Board Game Con & Tabletop Fair 2026: มหกรรมบอร์ดเกมระดับชาติ',
    rawDate: '31 ส.ค. 2026',
    rawTime: '10:30 - 20:30 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Hall 103)',
    rawPrice: '฿100 (เล่นได้ทั้งวัน)',
    rawDescription: 'งานรวมพลคนรักบอร์ดเกม มีโต๊ะให้ทดลองเล่นเกมใหม่ๆ ฟรีกว่า 300 โต๊ะ พร้อมโซนหาเพื่อนตี้ใหม่',
    rawImage: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bitec.co.th/events/boardgame-con',
  },
  {
    source: 'BMA_Bangkok',
    rawTitle: 'ดนตรีในสวน สวนลุมพินี (Lumpini Jazz & Acoustic Sunset)',
    rawDate: '5 ก.ย. 2026',
    rawTime: '16:30 - 19:30 น.',
    rawLocation: 'สวนลุมพินี (Lumpini Park)',
    rawPrice: 'ฟรี!',
    rawDescription: 'เทศกาลดนตรีแจ๊สและอะคูสติกยามเย็นกลางสวนสาธารณะ ปูเสื่อนั่งฟังเพลงรับลมธรรมชาติ',
    rawImage: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://pr-bangkok.com/events/music-park',
  },
  {
    source: 'QSNCC',
    rawTitle: 'Thailand Game Show & Cosplay Festival 2026: งานเกมและคอสเพลย์ยิ่งใหญ่',
    rawDate: '20 ก.ย. 2026',
    rawTime: '10:00 - 20:00 น.',
    rawLocation: 'ศูนย์การประชุมแห่งชาติสิริกิติ์ (QSNCC Exhibition Hall)',
    rawPrice: '฿150',
    rawDescription: 'มหกรรมเกมและคอสเพลย์ที่ยิ่งใหญ่ที่สุด ทดลองเล่นเกมใหม่ก่อนใคร พบปะสตรีมเมอร์และคอมมูนิตี้',
    rawImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.qsncc.com/events/tgs2026',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Cat Lovers & Pet Community Meetup: มีตติ้งทาสแมว & ช้อปสินค้าสัตว์เลี้ยง',
    rawDate: '27 ก.ย. 2026',
    rawTime: '11:00 - 19:00 น.',
    rawLocation: 'เมกาบางนา (Mega Bangna Pet Park)',
    rawPrice: 'ฟรี!',
    rawDescription: 'งานมีตติ้งคนรักสัตว์เลี้ยง พูดคุยแลกเปลี่ยนประสบการณ์ พร้อมตรวจสุขภาพสัตว์เลี้ยงฟรีโดยสัตวแพทย์',
    rawImage: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/pet-meetup',
  },
  {
    source: 'Zipevent',
    rawTitle: 'Silent Book Club Bangkok: นัดอ่านหนังสือเงียบๆ ในคาเฟ่อารีย์',
    rawDate: '4 ต.ค. 2026',
    rawTime: '14:00 - 17:00 น.',
    rawLocation: 'อารีย์ (Ari Quiet Cafe & Library)',
    rawPrice: '฿120 (รวมเครื่องดื่ม 1 แก้ว)',
    rawDescription: 'พกหนังสือเล่มโปรดมานั่งอ่านเงียบๆ ร่วมกับเพื่อนนักอ่าน บรรยากาศสงบ ผ่อนคลาย Introvert Friendly',
    rawImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.zipeventapp.com/e/silent-book-club',
  },
  {
    source: 'BITEC',
    rawTitle: 'Thailand International Craft Beer & Cider Festival 2026',
    rawDate: '10 ต.ค. 2026',
    rawTime: '16:00 - 23:00 น.',
    rawLocation: 'ไบเทค บางนา (BITEC Outdoor Plaza)',
    rawPrice: '฿300 (รวมแก้วที่ระลึก)',
    rawDescription: 'เทศกาลคราฟต์เครื่องดื่มและดนตรีอินดี้ ชิมคราฟต์โซดาและเครื่องดื่มมอลต์กว่า 150 แบรนด์ พร้อมฟู้ดทรัคชั้นนำ',
    rawImage: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    sourceUrl: 'https://www.bitec.co.th/events/craft-fest',
  }
];

export async function fetchLiveRawEvents(): Promise<ScrapedRawEvent[]> {
  return [...REAL_BANGKOK_EVENT_SEEDS];
}
